### get user with id of 1
get http://localhost:8080/info/1

### get user with id of 77293 which doesn't exist
get http://localhost:8080/info/77293

### register
POST http://localhost:8080/register
content-type: application/json

{
    "name":"zxk7517",
    "email":"zxk7517@foxmail.com",
    "password":"111111"
}

### login

POST http://localhost:8080/login
content-type: application/json

{
    "name":"zxk7517",
    "password": "111111"
}